CC = gcc
CFLAGS = -Wall -g -pthread
TARGETS = user1 user2
SRCS1 = user1.c
SRCS2 = user2.c
OBJS1 = $(SRCS1:.c=.o)
OBJS2 = $(SRCS2:.c=.o)
LIBS = -L. -lksocket -pthread

all: $(TARGETS)

user1: $(OBJS1) libksocket.a
	$(CC) $(CFLAGS) -o $@ $(OBJS1) $(LIBS)

user2: $(OBJS2) libksocket.a
	$(CC) $(CFLAGS) -o $@ $(OBJS2) $(LIBS)

%.o: %.c ksocket.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS1) $(OBJS2) $(TARGETS)

.PHONY: all clean