CC = gcc
CFLAGS = -Wall -g -pthread
AR = ar
ARFLAGS = rcs
TARGET = libksocket.a
SRCS = ksocket.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(AR) $(ARFLAGS) $@ $^

%.o: %.c ksocket.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean