# Library Makefile - builds the KTP socket library

CC = gcc
CFLAGS = -Wall -pthread
TARGET = libksocket.a
SRCS = ksocket.c
OBJS = $(SRCS:.c=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	ar rcs $@ $^

%.o: %.c ksocket.h
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean